### PR TITLE
FLTR-8425: Removed call to close the bottom sheet from _ModalBottomSheetState._handleDragUpdate

### PR DESCRIPTION
**Pull request by CraigZheng**
In this PR, the `_ModalBottomSheetState._handleDragUpdate()` will no longer dismiss the modal sheet.

### CODE REVIEW

**Comment by b-ray** [comment]
Let's wait for Max to review this please.
I feel like using this would be a better solution: https://github.com/jamesblasco/modal_bottom_sheet/pull/204/files?diff=unified&w=1

**Comment by mshibanami** [comment]
@max-insight
Ping, just in case 🙂

**Review by max-insight — COMMENTED** [review]
I think it's better Instead of removing the call, maybe better to be able to pass parameter and control with that?
I like what @b-ray suggested 
but maybe do it as next improvement?

**Comment by CraigZheng** [comment]
> I think it's better Instead of removing the call, maybe better to be able to pass parameter and control with that?
> I like what @b-ray suggested
> but maybe do it as next improvement?

Thanks @max-insight , I agree that making it optional would be a better choice, I will work on it now.
However, as mentioned by @b-ray , do you think this PR is still necessary after this PR https://github.com/jamesblasco/modal_bottom_sheet/pull/204/files?diff=unified&w=1

**Update**
After checking the mentioned PR, I found it does not affect the functionalities of the `ModalBottomSheet` library, it is not a substitute for this PR. I've misunderstood Stefan's comment.

I will add additional parameter to control the functionality of this PR.

**Comment by CraigZheng** [comment]
After further investigation, this PR is probably not needed - if we remove the `WillPopScope` from the modal bottom sheet, the dismissing of the modal bottom sheet should not have issue https://insight-timer.atlassian.net/browse/FLTR-8425 anymore.

image

**Pull request closed without merging**
